apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: eduquiz

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z mysql-db 3306; do echo waiting for mysql...; sleep 2; done;']

      containers:
      - name: backend

        image: backend-app:latest

        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8080

        envFrom:
        - configMapRef:
            name: backend-config